adpcm ball.pcm ball.adp 1
dmgcut ball.adp ball.4 48
adpcm rim.pcm rim.adp 1
dmgcut rim.adp rim.4 48
adpcm net.pcm net.adp 1
dmgcut net.adp net.4 48
adpcm whistle.pcm whistle.adp 1
dmgcut whistle.adp whistle.4 48
adpcm backbord.pcm backbord.adp 1
dmgcut backbord.adp backbord.4 48
adpcm rimsoft.pcm rimsoft.adp 1
dmgcut rimsoft.adp rimsoft.4 48
adpcm subhorn.pcm subhorn.adp 1
dmgcut subhorn.adp subhorn.4 48
adpcm catch.pcm catch.adp 1
dmgcut catch.adp catch.4 48
adpcm slam.pcm slam.adp 1
dmgcut slam.adp slam.4 48
adpcm squeak.pcm squeak.adp 1
dmgcut squeak.adp squeak.4 48
adpcm hit.pcm hit.adp 1
dmgcut hit.adp hit.4 48
adpcm fall.pcm fall.adp 1
dmgcut fall.adp fall.4 48
adpcm buzzer.pcm buzzer.adp 1
dmgcut buzzer.adp buzzer.4 48
adpcm cheer.pcm cheer.adp 1
dmgcut cheer.adp cheer.4 48
adpcm oh.pcm oh.adp 1
dmgcut oh.adp oh.4 48
adpcm rockyou.pcm rockyou.adp 1
dmgcut rockyou.adp rockyou.4 48
adpcm boo.pcm boo.adp 1
dmgcut boo.adp boo.4 48
