;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	       CONSTANT
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;MainProgBank  equ 5
a_2_a		equ	0
a_2_b		equ	2
b_2_b		equ	3
b_2_a		equ	1

CUR_SHAPE_BIT	EQU	7; 80H	   ;0 - BLOCK CURSOR, 1 - LINE CURSOR
CUR_SHAPE_LOC	EQU	80H

CUR_DISP_CYCLE	EQU	6; 40H	   ;0 - OFF, 1 - ON
CUR_DISP_LOC	EQU	40H

CUR_ON_BIT	EQU	5; 20H	   ;0 - OFF, 1 - ON
CUR_ON_BIT_LOC	EQU	20H


MAX_WIDTH	EQU	200
MAX_HEIGHT	EQU	160


