D2S	equ        10h                 ;77.782          FB2     77.775  0.01%
E2 	equ        11h                 ;82.407          ED0     82.410  0.00%
F2    	equ   	12H                 ;87.307          DFB     87.314  0.01%
F2S	equ       13H                 ;92.499          D32     92.510  0.01%
G2	equ       14H                 ;97.999          C75     98.024  0.03%
G2S	equ       15H                 ;103.830         BC2     103.821 0.01%
A2 	equ       16H                 ;110.000         B19
A2S	equ       17H                 ;116.541         A79
B2  	equ       18H                 ;123.471         9E3
                               ;
C3 	equ       19H                 ;130.813         955
C3S 	equ       1AH                 ;138.591         8CF
D3  	equ       1BH                 ;146.832         850
D3S	equ       1CH                 ;155.563         7D9
E3  	equ       1DH                 ;164.814         768
F3 	equ       1EH                 ;174.614         6FE
F3S	equ       1FH                 ;185.000         699
G3 	equ       20H                 ;196.000         63A
G3S 	equ       21H                 ;207.652         5E1
A3 	equ       22H                 ;220.000         58C
A3S	equ       23H                 ;233.082         53D
B3  	equ       24H                 ;246.942         4F1
                               ;
C4 	equ        25H                 ;261.626         4AA
C4S 	equ       26H                 ;277.183         467
D4 	equ        27H                 ;293.665         428
D4S	equ        28H                 ;311.127         3EC
E4	equ         29H                 ;329.628         3B4
F4 	equ        2AH                 ;349.228         37F
F4S	equ        2BH                 ;369.994         34D
G4 	equ        2CH                 ;391.995         31D
G4S 	equ       2DH                 ;415.305         2F0
A4 	equ        2EH                 ;440.000         2C6
A4S	equ        2FH                 ;466.164         29E
B4	equ         30H                 ;494.883         277
                               ;
C5 	equ        31H                 ;523.251         255
C5S	equ        32H                 ;554.364         234
D5 	equ        33H                 ;587.330         214
D5S 	equ       34H                 ;622.254         1F6
E5	equ         35H                 ;659.255         1DA
F5 	equ        36H                 ;698.456         1BF
F5S	equ        37H                 ;739.989         1A6
G5 	equ        38H                 ;783.991         18F
G5S	equ        39H                 ;830.609         178
A5	equ         3AH                 ;880.000         163
A5S 	equ       3BH                 ;932.328         14F
B5	equ         3CH                 ;987.767         13C

C6 	equ        3DH                 ;1046.502        12B
C6S	equ        3EH                 ;1108.731        11A
D6 	equ        3FH                 ;1174.660*       10A
D6S	equ        40H                 ;1244.508*       0FB
E6	equ         41H                 ;1318.510*       0ED
F6 	equ        42H                 ;1396.912*       0E0
F6S	equ        43H                 ;1479.978*       0D3
G6 	equ        44H                 ;1567.982*       0C7
G6S	equ        45H                 ;1661.218*       0BC
A6 	equ        46H                 ;1760.000*       0B2
A6S	equ        47H                 ;1864.656*       0A8
B6	equ         48H                 ;1975.534*       09E
                               ;
C7  	equ       49H                 ;2093.004*       095
C7S 	equ       4AH                 ;2217.456*       08D
D7	equ         4BH                 ;2349.320*       085
D7S	equ        4CH                 ;2489.016*       07E
E7 	equ        4DH                 ;2637.020*       077
F7	equ         4EH                 ;2793.824*       070
F7S	equ        4FH                 ;2959.956*       06A
G7 	equ        50H                 ;3135.964*       064
G7S	equ        51H                 ;3322.436*       05E
A7 	equ        52H                 ;3520.000*       059
A7S	equ        53H                 ;3729.312*       054
B7 	equ        54H                 ;3951.068*       04F
                               ;
C8 	equ        55H                 ;4186.008*       04B
;
PAUSE	equ	  80H		--   	--------	PAUSE
;
